server:
  port: 80
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 500
    min-spare-threads: 100
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/flash_sale?useUnicode=true&autoReconnect=true&useAffectedRows=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
  redis:
    database: 0
    host: localhost
    password: ''
    port: 6379
tiny.url:
  domain: tlyy.cn