server:
  port: 80
  tomcat:
    accept-count: 1000
    max-connections: 10000
    max-threads: 500
    min-spare-threads: 100
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/flash_sale?useUnicode=true&autoReconnect=true&useAffectedRows=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 70
      max-active: 70
      min-idle: 70
      max-wait: 5000
      filters: stat,wall,slf4j
      useGlobalDataSourceStat: true
  redis:
    database: 0
    host: localhost
    password: ''
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 20
        max-wait: 30
tiny.url:
  domain: tlyy.cn